Pytorch는 Tensorflow와 더불어 가장 널리 사용되는 딥러닝 프레임워크

다차원 배열인 Tensor를 기본 연산단위로 활용한다

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

1. 라이브러리 불러오기


In [1]:
import torch
import numpy as np

2. 텐서 만들기

* 텐서는 List와 Numpy Array에서 만들 수 있음

* 리스트는 파이썬에서 배열을 다루는 데이터 타입

* Numpy는 배열 연산을 위한 라이브러리로 데이터 과학에서 널리 사용됨

* Tensor는 numpy의 기능을 참고하여 딥러닝 연산에 필요한 기능들을 제공. 문법이 유사한 경우가 많음

In [2]:
# 리스트에서 만들기

data1 = [1,2,3]  # 리스트
t1= torch.tensor(data1)  # 텐서로 변환

In [3]:
print(data1)
print(t1)

# 출력형태가 리스트와 텐서가 다르게 나타남

[1, 2, 3]
tensor([1, 2, 3])


In [4]:
data2 = [[1,2,3],[4,5,6]] # 2차 배열
t2 = torch.tensor(data2)

In [5]:
# Numpy에서 만들기

data3= np.array([1,2,3]) # numpy 배열 만들기
t3 = torch.tensor(data3)

In [6]:
t3

tensor([1, 2, 3])

* 랜덤이나 상수로도 만들 수 있음

In [7]:
t4 = torch.rand(2,3) # 2 x 3 텐서만들기

In [8]:
t4

tensor([[0.0208, 0.2299, 0.6836],
        [0.3527, 0.7539, 0.8924]])

In [9]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

3. 텐서 속성

In [11]:
t4.shape  # 사이즈 확인

torch.Size([2, 3])

In [12]:
t4.dtype  # 데이터 타입 확인

torch.float32

In [13]:
t4.device # 저장 위치 확인

device(type='cpu')

4. 저장 위치
* 기본값은 CPU 저장이며, .to()를 사용하여 GPU로 옮길 수 있다.

* Colab에서는 런타임에서 런타임 유형을 GPU로 변경하면 GPU 사용 가능함

* cuda는 nvidia의 딥러닝 연산 엔진

In [14]:
# GPU 사용 확인

torch.cuda.is_available()  # GPU 사용 가능하면 True, 아니면 false

True

In [15]:
t4

tensor([[0.0208, 0.2299, 0.6836],
        [0.3527, 0.7539, 0.8924]])

In [16]:
t5=t4.to('cuda') # GPU로 옮김

In [17]:
t5

tensor([[0.0208, 0.2299, 0.6836],
        [0.3527, 0.7539, 0.8924]], device='cuda:0')

5. 텐서 연산
* 사칙연산 및 행렬 연산 가능함
  - 사칙연산은 동일 위치끼리 연산

In [18]:
t6 = torch.tensor([1,2,3])
t7 = torch.tensor([2,3,4])

In [19]:
t6+t7

tensor([3, 5, 7])

In [20]:
t6 * t7

tensor([ 2,  6, 12])

In [21]:
t7/t6

tensor([2.0000, 1.5000, 1.3333])

In [22]:
t6 @ t7  # 행렬 곱

tensor(20)

In [23]:
t5.T  # Transpose

tensor([[0.0208, 0.3527],
        [0.2299, 0.7539],
        [0.6836, 0.8924]], device='cuda:0')

6. 타입 및 디바이스 관련
* 파이토치의 타입은 파이썬 기본 타입보다 종류가 많음
https://pytorch.org/docs/stable/tensors.html
* 디바이스 다르면 연산 안 됨
* GPU 저장된 변수는 numpy로 변환 안됨

In [24]:
print(t6.dtype, t7.dtype)

torch.int64 torch.int64


In [25]:
# 데이터 타입 변경
t7 = t7.type(torch.float)

In [26]:
t8 = t7.to('cuda')

In [27]:
t7+t8

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Expected all tensors to be on the same device

연산은 같은 디바이스에만 가능함

In [28]:
t8.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

TypeError: can't convert cuda:0 device type tensor to numpy

numpy배열 변환 전에 CPU로 디바이스 옮겨야 가능함

In [29]:
t8.to('cpu').numpy()

array([2., 3., 4.], dtype=float32)

디바이스를 옮기는 것은 리소스를 많이 사용하므로 최소한으로 하는 것이 좋음

7. 인덱싱

* [start:end]
* start는 0부터, end는 미포함
* -1은 마지막을 의미

In [30]:
t9 = torch.rand(10)

In [31]:
t9

tensor([0.9830, 0.9632, 0.9807, 0.1785, 0.1485, 0.2744, 0.8764, 0.4689, 0.8323,
        0.4183])

In [32]:
t9[0]  # 첫번째

tensor(0.9830)

In [33]:
t9[1:5]

tensor([0.9632, 0.9807, 0.1785, 0.1485])

In [34]:
t9[-2:-1]  # 뒤에서 2번째 요소만 가져옴, -1은 end 자리이므로 미포함

tensor([0.8323])

In [35]:
t9[-2:]  # start나 end가 비어있으면 처음 또는 끝까지임

tensor([0.8323, 0.4183])

In [36]:
t9[:] # 시작과 끝이 생략되면 전부 다

tensor([0.9830, 0.9632, 0.9807, 0.1785, 0.1485, 0.2744, 0.8764, 0.4689, 0.8323,
        0.4183])

여러 차원 텐서도 동일한 기준이 적용됩니다.

In [37]:
# pytorch에서는 이미지를 [N, C, H, W] 로 지정합니다

t10 = torch.rand(2,3,5,5) # 5x5 RGB 이미지 2장 예시

In [38]:
t10

tensor([[[[0.0248, 0.4116, 0.5841, 0.0593, 0.1482],
          [0.7922, 0.3076, 0.9736, 0.2713, 0.1579],
          [0.0871, 0.9757, 0.9565, 0.5320, 0.1801],
          [0.1274, 0.5225, 0.0114, 0.1803, 0.5517],
          [0.2134, 0.2540, 0.7396, 0.0963, 0.3292]],

         [[0.3971, 0.5164, 0.4664, 0.2102, 0.4094],
          [0.6129, 0.0530, 0.8294, 0.7844, 0.6034],
          [0.4735, 0.7900, 0.1210, 0.2725, 0.5101],
          [0.6323, 0.3494, 0.7235, 0.3455, 0.5955],
          [0.1466, 0.3357, 0.7305, 0.2707, 0.5732]],

         [[0.8824, 0.1209, 0.4747, 0.3178, 0.4405],
          [0.1490, 0.7105, 0.1395, 0.0405, 0.8326],
          [0.3455, 0.6971, 0.0200, 0.0143, 0.5314],
          [0.5249, 0.3391, 0.4511, 0.0876, 0.2835],
          [0.6223, 0.0846, 0.5086, 0.6478, 0.2390]]],


        [[[0.3662, 0.2031, 0.6752, 0.8944, 0.9399],
          [0.0984, 0.7108, 0.7641, 0.8687, 0.6395],
          [0.8136, 0.8972, 0.9243, 0.0704, 0.6181],
          [0.9461, 0.4587, 0.1998, 0.1353, 0.8960],
    

In [39]:
img1 = t10[0] # 첫번째 이미지

In [40]:
img1

tensor([[[0.0248, 0.4116, 0.5841, 0.0593, 0.1482],
         [0.7922, 0.3076, 0.9736, 0.2713, 0.1579],
         [0.0871, 0.9757, 0.9565, 0.5320, 0.1801],
         [0.1274, 0.5225, 0.0114, 0.1803, 0.5517],
         [0.2134, 0.2540, 0.7396, 0.0963, 0.3292]],

        [[0.3971, 0.5164, 0.4664, 0.2102, 0.4094],
         [0.6129, 0.0530, 0.8294, 0.7844, 0.6034],
         [0.4735, 0.7900, 0.1210, 0.2725, 0.5101],
         [0.6323, 0.3494, 0.7235, 0.3455, 0.5955],
         [0.1466, 0.3357, 0.7305, 0.2707, 0.5732]],

        [[0.8824, 0.1209, 0.4747, 0.3178, 0.4405],
         [0.1490, 0.7105, 0.1395, 0.0405, 0.8326],
         [0.3455, 0.6971, 0.0200, 0.0143, 0.5314],
         [0.5249, 0.3391, 0.4511, 0.0876, 0.2835],
         [0.6223, 0.0846, 0.5086, 0.6478, 0.2390]]])

In [41]:
channel1 = t10[:, 0, :,:] # 0번째 컬러 채널만 가져오기

In [42]:
channel1

tensor([[[0.0248, 0.4116, 0.5841, 0.0593, 0.1482],
         [0.7922, 0.3076, 0.9736, 0.2713, 0.1579],
         [0.0871, 0.9757, 0.9565, 0.5320, 0.1801],
         [0.1274, 0.5225, 0.0114, 0.1803, 0.5517],
         [0.2134, 0.2540, 0.7396, 0.0963, 0.3292]],

        [[0.3662, 0.2031, 0.6752, 0.8944, 0.9399],
         [0.0984, 0.7108, 0.7641, 0.8687, 0.6395],
         [0.8136, 0.8972, 0.9243, 0.0704, 0.6181],
         [0.9461, 0.4587, 0.1998, 0.1353, 0.8960],
         [0.9053, 0.6240, 0.4369, 0.4833, 0.8149]]])

8. Tensor 차원 관련 수정

* 다른 라이브러리와 데이터 배열 형태가 다른 경우 변경이 필요합니다.

In [43]:
# 차원 늘이기

t11 = torch.rand(5,5) # 흑백 이미지 한장 예시

In [44]:
# batch, channel 추가하기

t12=t11.unsqueeze(dim=0)
print(t12.size())

torch.Size([1, 5, 5])


In [45]:
t13 = t12.unsqueeze(dim=0)

In [46]:
t13.size()

torch.Size([1, 1, 5, 5])

In [47]:
# 차원 줄이기

t13.squeeze().size()  # 1개인 차원이 모두 사라짐짐

torch.Size([5, 5])

In [48]:
t13.squeeze(dim=0).size() # 원하는 차원의 위치를 지정 가능함. 0부터 시작

torch.Size([1, 5, 5])

In [49]:
t13.squeeze(dim=2).size() # 차원이 1이 아니면 없어지지 않음, 데이터가 삭제되는 것을 방지

torch.Size([1, 1, 5, 5])

In [50]:
t13.permute(0,2,3,1).shape  # 컬러 채널 위치 변경

torch.Size([1, 5, 5, 1])