Neural Network 구성에 필수적인 nn.linear 함수를 알아봅시다.

https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

y = w*x + b를 계산할수 있습니다.
데이터 학습을 통해 데이터에 맞는 w와 b를 구할 수 있습니다

In [1]:
import torch
import torch.nn as nn

linear_layer = nn.Linear(1,1)

In [2]:
dir(linear_layer)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_per

In [3]:
# weight와 bias는 초기에 random값으로 입력됩니다. (실행할 때마다 다른 결과값이 나옵니다. )

print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[-0.1826]], requires_grad=True)
Parameter containing:
tensor([-0.6700], requires_grad=True)


In [4]:
x = torch.tensor([3.0])
y = linear_layer(x)
print(y)

tensor([-1.2178], grad_fn=<ViewBackward0>)
