pytorch는 뉴럴 네트워크 모델을 쉽게 만들 수 있는 nn.Sequential 클래스를 제공합니다

간단한 모델을 만들어보겠습니다

In [16]:
from torch import nn
import torch

model = nn.Sequential(
    nn.Linear(3, 6), #3개의 특성을 가진 (x1, x2, x3)
    nn.Linear(6, 1) # 최종적으로 1개의 출력값
)

In [17]:
type(model)

torch.nn.modules.container.Sequential

In [18]:
input_data = torch.randn(2, 3)  # 2개의 데이터 3개의 Feature
print(input_data)
output = model(input_data)  # Pass the input through the model
print(output)

tensor([[ 0.6489, -0.2448, -0.6157],
        [-0.2148,  0.7556,  0.0560]])
tensor([[0.0391],
        [0.0142]], grad_fn=<AddmmBackward0>)


In [19]:
print(model)

Sequential(
  (0): Linear(in_features=3, out_features=6, bias=True)
  (1): Linear(in_features=6, out_features=1, bias=True)
)


In [20]:
dir(model)

['T_destination',
 '__add__',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_item_by_idx',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_lo

In [21]:
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=3, out_features=6, bias=True)
  (1): Linear(in_features=6, out_features=1, bias=True)
)>

In [22]:
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[-0.2371,  0.4800,  0.2997],
        [-0.1245,  0.2961, -0.4290],
        [ 0.2808, -0.0601,  0.1338],
        [ 0.3791,  0.2313, -0.1560],
        [ 0.4404, -0.5109, -0.0508],
        [-0.5770,  0.2672,  0.2288]], requires_grad=True)
Parameter containing:
tensor([ 0.2024,  0.4087, -0.3607, -0.0047,  0.2811,  0.0556],
       requires_grad=True)
Parameter containing:
tensor([[-0.0231,  0.0938, -0.1569,  0.0138, -0.1864, -0.2375]],
       requires_grad=True)
Parameter containing:
tensor([-0.0480], requires_grad=True)


In [23]:
for key, value  in model.named_parameters():
  print(key)
  print(value)

0.weight
Parameter containing:
tensor([[-0.2371,  0.4800,  0.2997],
        [-0.1245,  0.2961, -0.4290],
        [ 0.2808, -0.0601,  0.1338],
        [ 0.3791,  0.2313, -0.1560],
        [ 0.4404, -0.5109, -0.0508],
        [-0.5770,  0.2672,  0.2288]], requires_grad=True)
0.bias
Parameter containing:
tensor([ 0.2024,  0.4087, -0.3607, -0.0047,  0.2811,  0.0556],
       requires_grad=True)
1.weight
Parameter containing:
tensor([[-0.0231,  0.0938, -0.1569,  0.0138, -0.1864, -0.2375]],
       requires_grad=True)
1.bias
Parameter containing:
tensor([-0.0480], requires_grad=True)


층별 연산이 어떻게 되는지 확인해봅시다


In [24]:
layer_outputs = []

for i,layer in enumerate(model.children()):
  input_data = layer(input_data)
  print(layer)
  print(f'layer {i}')
  print(input_data)
  layer_outputs.append(input_data)


Linear(in_features=3, out_features=6, bias=True)
layer 0
tensor([[-0.2535,  0.5196, -0.2461,  0.2807,  0.7232, -0.5250],
        [ 0.6328,  0.6351, -0.4590,  0.0799, -0.2024,  0.3943]],
       grad_fn=<AddmmBackward0>)
Linear(in_features=6, out_features=1, bias=True)
layer 1
tensor([[0.0391],
        [0.0142]], grad_fn=<AddmmBackward0>)
